alertmanager:
  enabled: false

prometheus-pushgateway:
  enabled: false

server:
  persistentVolume:
    enabled: false
  retention: "6h"

kube-state-metrics:
  enabled: true

prometheus-node-exporter:
  enabled: true
